server:
  servlet:
    context-path: /wx-sell
spring:
    datasource:
       driver-class-name: com.mysql.jdbc.Driver
       username: root
       password: 123456
       url: jdbc:mysql://192.168.41.65/sell?characterEncoding=utf-8&useSSL=false
    jpa:
       show-sql: true
       hibernate:
         naming:
           physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl